### ISSUE TITLE
Empty Installation?

### ISSUE THREAD

**Issue by markercraig** [riscv/homebrew-riscv#4]
I follow the instructions exactly, and end up receiving this error: 

==> Installing riscv-tools from riscv/riscv
==> Downloading https://github.com/riscv/riscv-tools/archive/homebrew.tar.gz
Already downloaded: /Library/Caches/Homebrew/riscv-tools-0.1.tar.gz
Error: Empty installation

Any thoughts?

**Comment by alansuphd** [comment]
I have exactly the same problem. "brew update" twice then fix all warnings reported by "brew doctor" and the problem persists. Any feedback/solutions are highly appreciated.

**Comment by sbeamer** [comment]
Thank you for the report. This was caused by a commit to Homebrew (https://github.com/Homebrew/homebrew/commit/915ac06db21acc5c9595b2223cc39b9672f34c4a) which Travis didn't detect because it is running an older version of Homebrew. We use riscv-tools as an alias to install the needed repos and contain a trivial hello world test, but it is an "empty installation" as now blocked by Homebrew.
